version: "3.7"
# to get in interactive shell to generate components
# docker run, runs a command in a new container
# docker run -it -v $(pwd):/app node:16-alpine bash
#
# to run commands in a running container
# docker exec -it <container_id> sh
# or 
# docker-compose exec app sh

services:
  app:
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    image: node:16-alpine
    command: sh -c "yarn global add @angular/cli && yarn install && ng serve --host 0.0.0.0"
    ports:
       - 4200:4200
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: node:16-alpine
    command: sh -c "yarn global add json-server && json-server --watch db.json --host 0.0.0.0"
    ports:
       - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app   